// This file was auto-generated by ast_dumper.rs

[
    VarDeclaration(
        Name {
            value: "aNumber",
        },
        Int,
        IntLit(
            8192,
        ),
    ),
    VarDeclaration(
        Name {
            value: "aString",
        },
        String,
        StringLit(
            "hello world",
        ),
    ),
]