[package]
name = "lune"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "lune"

[lib]
path = "src/lang/lang.rs"
name = "lune"

[dependencies]
lazy_static = "1.4.0"