# Grammar for Lune

expression  ::= equality;

literal     ::= <Number> | <String> | "null";
equality    ::= comparison ( ("!=" | "==" ) comparison)*;
comparison  ::= term ( (">" | ">=" | "<" | "<= ") term)*;

# a term is zero or more factors
term        ::= factor ( ("-" | "+") factor)*;
factor      ::= unary ( ("*" | "/") unary)*;
unary       ::= ("!" | "-") unary
             | primary_expr;

# variable declaration
var_declare ::= "var" <Identifier> : <Type> "=" primary;
if_statement ::= "if" equality "{" block "}" "else" "{" block "}"; 

primary     ::= literal 
             | "(" expression ")";

block       ::= statement*;
statement   ::= var_declare
             | primary;

# root node
root        ::= statement*;