use super::ast::*;
use std::fs::File;
use std::io::{BufWriter, Write};

pub struct ASTDumper;

impl ASTDumper {
    /// Dump the unvisited AST to a file
    pub fn dump_ast(&self, ast: AST) {
        let header = "// This file was auto-generated by ast_dumper.rs\n\n";

        let dump = format!("{:#?}", ast);

        let file = File::create("ast_dump.rs").expect("unable to create file");
        let mut writer = BufWriter::new(file);

        // Write the header comment
        writer.write_all(header.as_bytes()).expect("failed to write");

        // .. and write the AST
        writer.write_all(&dump.as_bytes()).expect("unable to write");
    }
}
